"use client";

import { useState } from "react";
import { useAction, useMutation, useQuery } from "convex/react";
import { api } from "../../convex/_generated/api";
import type { Id } from "../../convex/_generated/dataModel";
import { GarmentCard } from "./GarmentCard";
import { Button, CountUp, Reveal, ScoreBar, SectionLabel } from "./primitives";
import { WeatherStrip } from "./WeatherStrip";
import { MissingPiece } from "./MissingPiece";
import { clsx } from "clsx";

const SLOT_ORDER = ["top", "layer", "bottom", "shoes", "accessory"];

export function OutfitResult({ sessionId }: { sessionId: Id<"recommendationSessions"> }) {
  const data = useQuery(api.recommend.session, { sessionId });
  const [alternate, setAlternate] = useState(0);
  const [swapping, setSwapping] = useState<string | null>(null);

  const submitFeedback = useMutation(api.feedback.submit);
  const markWorn = useMutation(api.wardrobe.markWorn);
  const swapItem = useAction(api.recommend.swapItem);

  if (data === undefined) {
    return (
      <div className="rule mt-14 pt-10">
        <div className="skeleton h-8 w-48" />
      </div>
    );
  }
  if (data === null) return null;

  const { session, outfits } = data;
  const current = outfits[Math.min(alternate, outfits.length - 1)];
  if (!current) return null;

  const { outfit, items, feedback } = current;
  const sorted = [...items].sort(
    (a, b) => SLOT_ORDER.indexOf(a.slot) - SLOT_ORDER.indexOf(b.slot),
  );

  const heading = alternate === 0 ? headingFor(session.intent.timeOfDay) : "Another option";

  async function handleWear() {
    await submitFeedback({ outfitId: outfit._id, verdict: "wear" });
    await markWorn({ outfitId: outfit._id });
  }

  async function handleSwap(slot: string) {
    setSwapping(slot);
    try {
      await swapItem({ outfitId: outfit._id, slot });
    } finally {
      setSwapping(null);
    }
  }

  return (
    <>
      {/* -------------------------------------------------------- context strip */}
      <section className="rule mt-14 pt-8">
        <WeatherStrip weather={session.weather} intent={session.intent} />
      </section>

      {/* ----------------------------------------------------------- the outfit */}
      <section className="mt-12">
        <div className="flex flex-wrap items-end justify-between gap-6">
          <Reveal>
            <h2 className="display text-[clamp(2.2rem,5.5vw,3.6rem)]">{heading}</h2>
          </Reveal>
          <Reveal delay={120}>
            <div className="flex items-baseline gap-2">
              <CountUp
                value={outfit.overallScore}
                className="display text-[clamp(3rem,9vw,5.2rem)] leading-none"
                suffix="%"
              />
              <span className="label mb-2">match</span>
            </div>
          </Reveal>
        </div>

        {/* garments — the column count follows the outfit so there's no dead cell */}
        <div
          className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:[grid-template-columns:repeat(var(--outfit-cols),minmax(0,1fr))]"
          style={{
            ["--outfit-cols" as string]: String(Math.min(5, Math.max(3, sorted.length))),
          }}
        >
          {sorted.map(
            (entry, i) =>
              entry.item && (
                <Reveal key={`${entry.slot}-${entry.item._id}`} delay={150 + i * 90}>
                  <div className="group/slot relative">
                    <GarmentCard item={entry.item} slot={entry.slot} size="large" />
                    {entry.slot !== "accessory" && (
                      <button
                        type="button"
                        onClick={() => void handleSwap(entry.slot)}
                        disabled={swapping !== null}
                        className="absolute right-3 top-3 rounded-full bg-paper/90 px-3 py-1.5 text-[0.7rem] opacity-0 backdrop-blur-sm transition-opacity hover:bg-paper group-hover/slot:opacity-100 disabled:opacity-40"
                      >
                        {swapping === entry.slot ? "…" : "Swap"}
                      </button>
                    )}
                  </div>
                </Reveal>
              ),
          )}
        </div>

        {/* explanation */}
        <Reveal delay={520}>
          <p className="display mt-10 max-w-[54ch] text-[clamp(1.2rem,2.4vw,1.6rem)] leading-snug">
            {outfit.explanation}
          </p>
          {outfit.explanationSource === "engine" && (
            <p className="label mt-3 text-[0.58rem]">Generated by the scoring engine</p>
          )}
        </Reveal>

        {/* actions */}
        <Reveal delay={600}>
          <div className="mt-9 flex flex-wrap items-center gap-3">
            <Button onClick={() => void handleWear()} disabled={feedback === "wear"}>
              {feedback === "wear" ? "Wearing this" : "Wear this"}
            </Button>
            <Button
              variant="secondary"
              onClick={() => void submitFeedback({ outfitId: outfit._id, verdict: "reject" })}
              disabled={feedback === "reject"}
            >
              {feedback === "reject" ? "Noted — not you" : "Not me"}
            </Button>
            {outfits.length > 1 && (
              <Button
                variant="ghost"
                onClick={() => setAlternate((n) => (n + 1) % outfits.length)}
              >
                Try another ({outfits.length - 1} more)
              </Button>
            )}
          </div>
          {feedback && (
            <p className="label mt-4 text-[0.6rem]">
              GRWM updated your style profile — the next fit will reflect this.
            </p>
          )}
        </Reveal>
      </section>

      {/* ------------------------------------------------------- why this works */}
      <section className="rule mt-16 pt-10">
        <SectionLabel>Why this works</SectionLabel>
        <div className="mt-8 grid gap-x-14 gap-y-7 sm:grid-cols-2">
          {outfit.reasons.map((reason, i) => (
            <Reveal key={reason.label} delay={i * 70}>
              <div>
                <div className="flex items-baseline justify-between gap-4">
                  <span className="text-[0.95rem]">{reason.label}</span>
                  <span className="nums text-[0.95rem]">{reason.score}%</span>
                </div>
                <div className="mt-2.5">
                  <ScoreBar
                    value={reason.score}
                    delay={200 + i * 90}
                    tone={
                      reason.score >= 85
                        ? "ink"
                        : reason.score >= 65
                          ? "warn"
                          : "bad"
                    }
                  />
                </div>
                <p className="mt-2.5 text-[0.85rem] leading-relaxed text-slate">
                  {reason.text}
                </p>
              </div>
            </Reveal>
          ))}
        </div>

        {/* alternates strip */}
        {outfits.length > 1 && (
          <div className="mt-12">
            <SectionLabel>Runners-up</SectionLabel>
            <div className="mt-5 flex flex-wrap gap-2">
              {outfits.map((option, i) => (
                <button
                  key={option.outfit._id}
                  type="button"
                  onClick={() => setAlternate(i)}
                  className={clsx(
                    "rounded-full border px-4 py-2 text-[0.8rem] transition-colors",
                    i === alternate
                      ? "border-ink bg-ink text-paper"
                      : "border-clay/45 text-slate hover:border-ink/40",
                  )}
                >
                  <span className="nums">{option.outfit.overallScore}%</span>
                  <span className="ml-2 opacity-70">{summarize(option.items)}</span>
                </button>
              ))}
            </div>
          </div>
        )}
      </section>

      {/* ------------------------------------------------------- missing piece */}
      <MissingPiece sessionId={sessionId} baselineScore={outfit.overallScore} />
    </>
  );
}

/** Top + bottom + shoes, so alternates are actually distinguishable. */
function summarize(
  items: Array<{ slot: string; item: { name: string } | null }>,
): string {
  return ["top", "bottom", "shoes"]
    .map((slot) => items.find((entry) => entry.slot === slot)?.item?.name.toLowerCase())
    .filter(Boolean)
    .join(" · ");
}

function headingFor(timeOfDay: string): string {
  switch (timeOfDay) {
    case "morning":
      return "This morning's fit";
    case "afternoon":
      return "Today's fit";
    case "evening":
    case "night":
      return "Tonight's fit";
    default:
      return "Your fit";
  }
}
